[package]
name = "json-hydrate-benchmark"
version = "0.0.0"
edition = "2021"

[lib]
name = "json_hydrate_benchmark"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
pyo3 = { version = "0.19.0", features = ["anyhow"] }
pythonize = "0.19"
serde_json = "1"
